name: Go Build, Test, and Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.21.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Run Test
      run: go test ./...

    - name: Lint with staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: latest
        install-go: false
